### ISSUE TITLE
Receiving seat reservations from messages

### ISSUE THREAD

**Issue by kotwys** [colyseus/colyseus-hx#37]
When I send a seat reservation to a client via message, it comes to them like this (it looks like that fields and values are jumbled):

```
Object
  null: null
  room:
    0: 1
    116: null
    clients: 1
    createdAt: null
    null: null
```

Obviously they can’t consume that and the logs say the seat reservation is expired.

If I send it encoded in JSON and decoded back, everything works. Maybe this is because reservations have a recursive structure (as I could find out `console.log`ging it).

**Comment by endel** [comment]
Thanks for reporting @kotwys, it turns out the msgpack decoder wasn't supporting `"undefined"` and `Date` extension types. I've added some tests for decoding these types.

This weekend I've been working on a GitHub workflow to automatically publish packages to haxelib as well! https://github.com/endel/haxelib-publish-github-actions-test

So [this commit](https://github.com/colyseus/colyseus-hx/commit/9084228eb318247c1bd6f900daaee70511ce43e1) resulted in both creating:
- A GitHub Release: https://github.com/colyseus/colyseus-hx/releases/tag/0.13.3
- Submitting to Haxelib :tada: :tada:  https://lib.haxe.org/p/colyseus/0.13.3/

Let me know if you face any other issues! Cheers!
